# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Why Nelson"
url = "about/index.html"
weight = 2

[[main]]
name = "Testimonials"
url = "blog/index.html"
weight = 3

#[[main]]
#weight = 4
#name = "Pages"
#hasChildren = true

#  [[main]]
#  parent = "Pages"
#  name = "Blog Details"
#  url = "blog/post-1/"
#  weight = 1

#  [[main]]
#  parent = "Pages"
#  name = "Terms & Conditions"
#  url = "terms-and-conditions/"
#  weight = 7
  
[[main]]
name = "Contact"
url = "contact/index.html"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/index.html"
weight = 1

[[footer]]
name = "Blog"
url = "blog/index.html"
weight = 2

[[footer]]
name = "Blog Details"
url = "blog/post-1/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/index.html"
weight = 4